# Re-export everything from feature modules for backward compatibility
from .bar import plot_bar, plot_grouped_bar, plot_stacked_bar
from .charts import plot_box, plot_errorbar, plot_heatmap, plot_scatter
from .draw import draw, draw_bar
from .line import plot_line
from .styles import (
    available_fonts,
    available_layouts,
    available_text_colors,
    available_themes,
    configure_plot_style,
    despine,
    figure_size,
    format_axes,
    get_current_style,
    use_style,
)
from .utils import (
    annotate_points,
    blend_color,
    colors,
    format_legend,
    get_output_dir,
    markers,
    new_alpha,
    panel_labels,
    save,
    save_all,
    set_output_dir,
    theme_preview,
)

__all__ = [
    "plot_line",
    "plot_bar",
    "plot_grouped_bar",
    "plot_stacked_bar",
    "plot_scatter",
    "plot_errorbar",
    "plot_box",
    "plot_heatmap",
    "draw",
    "draw_bar",
    "configure_plot_style",
    "available_fonts",
    "available_layouts",
    "available_text_colors",
    "available_themes",
    "figure_size",
    "format_axes",
    "format_legend",
    "despine",
    "get_current_style",
    "use_style",
    "save",
    "save_all",
    "set_output_dir",
    "get_output_dir",
    "panel_labels",
    "annotate_points",
    "theme_preview",
    "colors",
    "markers",
    "new_alpha",
    "blend_color",
]
